### ISSUE TITLE
Support Sign1 messages

### ISSUE THREAD

**Issue by g-k** [mozilla-services/go-cose#4]

**Comment by thomas-fossati** [comment]
We implemented Sign1 in Veraison: https://github.com/mozilla-services/go-cose/compare/master...veraison:master

**Comment by g-k** [comment]
Cool! I'd be happy to review a PR if you want to land it in go-cose.

**Comment by hwine** [comment]
We are no longer making changes to this repository. See [README update](https://github.com/mozilla-services/go-cose#caution) for more information on the successor project.
