### ISSUE TITLE
Pass io.Reader as payload for signature

### ISSUE THREAD

**Issue by jvehent** [mozilla-services/go-cose#57]
Signing a message currently requires copying the payload as an `[]byte` into the `cose.SignMessage.Payload` field. For large payloads, this means copying large amounts of data. It also means the max size of a payload is limited by available memory.

Payloads are hashed and this can be done in chunks to avoid loading all that data into memory. Passing an `io.Reader` as Payload, perhaps as a PayloadReader variable, would allow the `Sign()` function to use that instead of the large `[]byte`

**Comment by hwine** [comment]
We are no longer making changes to this repository. See [README update](https://github.com/mozilla-services/go-cose#caution) for more information on the successor project.
