### ISSUE TITLE
CBOR library exhausts memory in 1 decode attempt of < 10 bytes of malformed CBOR data

### ISSUE THREAD

**Issue by x448** [mozilla-services/go-cose#62]
@g-k 🔥 this CBOR security issue is already public knowledge and affects a library used by go-cose.

__October 2013__ - RFC 7049 (CBOR) is approved by IETF as an Internet Standard and RFC 7049 Section 8 describes security considerations such as malicious CBOR.

__September 2019__ - oasislabs finds tiny malformed CBOR data causes fatal out of memory error when decoded with latest releases of ugorji/go (CBOR library used by go-cose) and switched to fxamacker/cbor in early October 2019.

__February 2020__ - smartcontractkit/chainlink has a security issue with ugorji/go that is closed by switching to fxamacker/cbor.  I don't have login access to view their security issue.

__March 2020__ - @fxamacker finds tiny malformed CBOR data that causes fatal out of memory error when decoded with [any release of ugorji/go (1.1.0 - 1.1.7 as well as last commit 42bc974)](https://github.com/fxamacker/cbor/issues/208).

![alt text](https://github.com/fxamacker/images/raw/master/cbor/v2.2.0/cbor_security_march2020_638px.svg?sanitize=1 "CBOR Security Comparison")

#### __[fxamacker/cbor](https://github.com/fxamacker/cbor/blob/master/README.md)__ comparisons to ugorji/go.

__Click to expand:__

<details>
  <summary>CBOR Program Size Comparison</summary><p>
  
__fxamacker/cbor__ can produce smaller programs.
  
![alt text](https://github.com/fxamacker/images/raw/master/cbor/v2.2.0/cbor_size_comparison.png "CBOR library and program size comparison chart")

</details>

<details>
  <summary>CBOR Speed Comparison</summary><p>

__fxamacker/cbor__ can be faster for CBOR data such as CBOR Web Tokens.

![alt text](https://github.com/fxamacker/images/raw/master/cbor/v2.2.0/cbor_speed_comparison.png "CBOR library speed comparison chart")

</details>

<details>
  <summary>CBOR Memory Comparison</summary><p>

__fxamacker/cbor__ can use less memory for CBOR data such as CBOR Web Tokens.

![alt text](https://github.com/fxamacker/images/raw/master/cbor/v2.2.0/cbor_memory_table.svg?sanitize=1 "CBOR Memory Comparison")

</details>

Benchmarks used example data from [RFC 8392 Appendix A.1](https://tools.ietf.org/html/rfc8392#appendix-A.1) and default options for CBOR libraries.

**Comment by x448** [comment]
The security comparison table was updated today to show the entire fatal error message.  It was previously showing the error text from the Sep 2019 data instead of Mar 2020 data.

**Comment by g-k** [comment]
Hey @x448, thanks for bringing this up! Seems like something that GH should've published an advisory for. 

I'll try to get to this by the end of April. I'm open to PRs swapping in the new CBOR encoder/decoder in the meantime.

:+1: `keyasint` and `toarray` look like they'll help simplify things and getting something properly fuzzed that doesn't use `unsafe` would be big wins too.

**Comment by x448** [comment]
@g-k great!  I think @fxamacker would be interested in opening a PR to handle the CBOR aspect.

I have an idea for another PR, I'll open a ticket.

**Comment by fxamacker** [comment]
Hi @g-k, I would love to open a PR and contribute to go-cose!  

I can begin work on go-cose right after wrapping up a task due Monday.

**Comment by g-k** [comment]
Awesome! That'd be great.

**Comment by fxamacker** [comment]
I've been reading COSE RFC 8152 (the parts used by go-cose) and so far so good.

**Comment by fxamacker** [comment]
@g-k I've been working on go-cose and will try to open a PR soon.
