### ISSUE TITLE
cose-rust round trip fails

### ISSUE THREAD

**Issue by g-k** [mozilla-services/go-cose#7]
Specifically: https://github.com/mozilla-services/go-cose/blob/ab7ab6410aec138f2bea0cb137635812d5577356/sign_verify_cose_rust_cli_test.go#L79

Maybe NSS is doing additional validation on the CERT chain?

**Comment by hwine** [comment]
We are no longer making changes to this repository. See [README update](https://github.com/mozilla-services/go-cose#caution) for more information on the successor project.
