### ISSUE TITLE
make sure COSE wg examples are up to date

### ISSUE THREAD

**Issue by g-k** [mozilla-services/go-cose#73]
It's OK if the test cases fail, but it'd be good to update them.

**Comment by niceoneallround** [comment]
Both the examples fail for me with "hash function is not available",  resolved by importing  _ "crypto/sha256". Added to this issue as seemed the same.

go run example/sign.go
panic: Error signing the message hash function is not available

This was resolved by importing
    _ "crypto/sha256"

So now if run 
go run example/sign.go
Message signature (ES256): 34adc2ae2fe83bb97047bed291f98874da23671e400b6f3592d78f1792c33965351ababb34199ca3bed900f63804e3f81ba03a2aa97fec0e2636b63b49c2c7b9

**Comment by hwine** [comment]
We are no longer making changes to this repository. See [README update](https://github.com/mozilla-services/go-cose#caution) for more information.
