### ISSUE TITLE
Question: Is this library still maintained?

### ISSUE THREAD

**Issue by dlorenc** [mozilla-services/go-cose#78]
I've been looking for a Go implementation of COSE and this is the only one I could find.

Is it still maintained/supported? Some of the issues/PRs are quite stale, and I'm wondering if it would be worth contributing fixes/improvements back up here.

**Comment by hwine** [comment]
Sorry for the delay in response - yes, it's still maintained to the extent Mozilla needs. We do want to allow for more active development from the community, and are working on that.

Thanks for your interest!

**Comment by hwine** [comment]
We are no longer making changes to this repository. See [README update](https://github.com/mozilla-services/go-cose#caution) for more information on the successor project.
