### ISSUE TITLE
are we using the right RSAPSS salt padding?

### ISSUE THREAD

**Issue by g-k** [mozilla-services/go-cose#8]
The spec says to use a salt length matching the hash length (i.e. `rsa.PSSSaltLengthEqualsHash`)

However, [go-jose](https://github.com/square/go-jose/blob/48bd10544821cc148898af271a64c5fc3f25115f/asymmetric.go#L262) uses the auto length salt padding for the PS256 and switching it fixes the RSA verify failure for #7.

**Comment by hwine** [comment]
We are no longer making changes to this repository. See [README update](https://github.com/mozilla-services/go-cose#caution) for more information on the successor project.
